# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-18 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='histo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histogram', models.CharField(max_length=250, unique=True)),
                ('image_title', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='histo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.histo'),
        ),
    ]
